# Generated by Django 3.1.7 on 2022-04-10 09:13

import autoskola.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odpoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odpoved', models.TextField(max_length=150)),
            ],
            options={
                'verbose_name': 'Odpověď',
                'verbose_name_plural': 'Odpovědi',
            },
        ),
        migrations.CreateModel(
            name='Otazka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otazka', models.TextField(max_length=150)),
                ('obrazek', models.ImageField(upload_to=autoskola.models.get_image_otazky)),
                ('odpoved_a', models.TextField(max_length=150)),
                ('odpoved_b', models.TextField(max_length=150)),
                ('odpoved_c', models.TextField(max_length=150)),
                ('spravna_odpoved', models.TextField(max_length=150)),
            ],
            options={
                'verbose_name': 'Otázka',
                'verbose_name_plural': 'Otázky',
            },
        ),
        migrations.CreateModel(
            name='Zakon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(max_length=50)),
                ('nazev', models.TextField(max_length=300)),
                ('typ', models.CharField(choices=[('Z', 'Zakon'), ('V', 'Vyhlaska')], default='Z', max_length=1)),
            ],
            options={
                'verbose_name': 'Zákon',
                'verbose_name_plural': 'Zákony',
            },
        ),
        migrations.CreateModel(
            name='Znacka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo', models.CharField(max_length=10)),
                ('obrazek', models.ImageField(upload_to=autoskola.models.get_image_path)),
                ('nazev', models.CharField(max_length=50)),
                ('vyznam', models.TextField(max_length=500)),
                ('typ', models.CharField(choices=[('A', 'Výstražné'), ('P', 'Upravující přednost'), ('B', 'Zákazové'), ('C', 'Příkazové'), ('IZ', 'Informativní zónové'), ('IP', 'Informativní provozní'), ('IS', 'Informativní směrové'), ('IJ', 'Informativní jiné'), ('E', 'Dodatkové tabulky'), ('1', 'Kulturní a turistické piktogramy'), ('2', 'Druhy vozidel a skupiny chodců'), ('3', 'Jiné a cíle'), ('4', 'Ostatní symboly'), ('V', 'Vodorovné dopravní značky'), ('S', 'Světelné signály'), ('Z', 'Dopravní zařízení'), ('ZPI', 'Dopravní zařízení'), ('O', 'Speciální označení vozidel a parkovací průkaz označující vozidlo přepravující osobu těžce zdravotně postiženou')], default='A', max_length=110)),
            ],
            options={
                'verbose_name': 'Značka',
                'verbose_name_plural': 'Značky',
            },
        ),
        migrations.CreateModel(
            name='Odstavec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraf', models.CharField(max_length=20)),
                ('odstavec', models.IntegerField()),
                ('obsah', models.TextField(max_length=500)),
                ('FK_zakon', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autoskola.zakon')),
            ],
            options={
                'verbose_name': 'Odstavec',
                'verbose_name_plural': 'Odstavce',
            },
        ),
    ]
