# Generated by Django 3.1.7 on 2022-04-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoskola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odpoved',
            name='FK_otazka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autoskola.otazka'),
        ),
        migrations.AddField(
            model_name='odpoved',
            name='timestamp',
            field=models.DateField(default='2022-10-10'),
        ),
        migrations.AddField(
            model_name='otazka',
            name='FK_odstavec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autoskola.odstavec'),
        ),
        migrations.AddField(
            model_name='otazka',
            name='FK_znacka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autoskola.znacka'),
        ),
    ]
