# Generated by Django 3.1.7 on 2022-04-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoskola', '0002_auto_20220410_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odpoved',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
