# Generated by Django 3.1.7 on 2022-08-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoskola', '0003_auto_20220809_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='otazka',
            name='orig_topic',
            field=models.CharField(choices=[('Pojmy', 'Zákon č. 361/2000Sb. (Pojmy, povinnosti)'), ('Jizda', 'Zákon č. 361/2000Sb. (Jízda vozidly)'), ('Ostatni', 'Zákon č. 361/2000Sb. (Ostatní ustanovení)'), ('Znacky', 'Dopravní značky'), ('Situace', 'Řešení dopravních situací'), ('BezpecnostA', 'Zásady bezpečné jízdy [A]'), ('BezpecnostB', 'Zásady bezpečné jízdy [B]'), ('BezpecnostCD', 'Zásady bezpečné jízdy [C,D]'), ('Predpisy', 'Související předpisy'), ('Provoz', 'Podmínky provozu vozidel'), ('Zdravi', 'Zdravotnická příprava'), ('Default', 'default')], default='default', max_length=12),
        ),
    ]
