# Generated by Django 3.1.7 on 2022-04-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoskola', '0003_auto_20220410_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odstavec',
            name='paragraf',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='otazka',
            name='spravna_odpoved',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='zakon',
            name='typ',
            field=models.CharField(choices=[('Z', 'Zákon'), ('V', 'Vyhláška')], default='Z', max_length=1),
        ),
        migrations.AlterField(
            model_name='znacka',
            name='typ',
            field=models.CharField(choices=[('A', 'Výstražné'), ('P', 'Upravující přednost'), ('B', 'Zákazové'), ('C', 'Příkazové'), ('IZ', 'Informativní zónové'), ('IP', 'Informativní provozní'), ('IS', 'Informativní směrové'), ('IJ', 'Informativní jiné'), ('E', 'Dodatkové tabulky'), ('1', 'Kulturní a turistické piktogramy'), ('2', 'Druhy vozidel a skupiny chodců'), ('3', 'Jiné a cíle'), ('4', 'Ostatní symboly'), ('V', 'Vodorovné dopravní značky'), ('S', 'Světelné signály'), ('Z', 'Dopravní zařízení'), ('ZPI', 'Dopravní zařízení'), ('O', 'Speciální označení vozidel a parkovací průkaz označující vozidlo přepravující osobu těžce zdravotně postiženou')], default='A', max_length=3),
        ),
    ]
