# Generated by Django 3.1.7 on 2022-04-10 10:13

import autoskola.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoskola', '0004_auto_20220410_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otazka',
            name='obrazek',
            field=models.ImageField(blank=True, upload_to=autoskola.models.get_image_otazky),
        ),
    ]
