# Generated by Django 3.1.7 on 2022-04-10 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoskola', '0005_auto_20220410_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otazka',
            name='FK_odstavec',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='autoskola.odstavec'),
        ),
        migrations.AlterField(
            model_name='otazka',
            name='FK_znacka',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='autoskola.znacka'),
        ),
    ]
